name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false  # Add this line to disable the wrapper

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Apply
        id: terraform_apply
        run: terraform apply -auto-approve
        working-directory: terraform/

      - name: Get EC2 Username
        id: ec2_username
        run: echo "username=$(terraform output -raw ec2_username | tr -d '\n')" >> $GITHUB_ENV
        working-directory: terraform/

  build_and_deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: likhithatangudu/webapp:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Using Terraform output
          username: ${{ env.username }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          script: |
            sudo yum install -y docker || sudo apt-get install -y docker.io
            sudo service docker start || sudo systemctl start docker
            docker stop webapp || true
            docker rm webapp || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
            docker run -d --name webapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}
